### DISCUSSION TITLE
How to make requests to Stable Difussion models through Hugging Face?

### DISCUSSION THREAD

**Discussion by wenlzhang** [nhaouari/obsidian-textgenerator-plugin#52] [Q&A]
I tried to create a template by modifying existing ones for Hugging Face and DALL E, then I came up with the following one. However, when I tried to make a request with the prompt "An astronaut riding a horse on Mars", I got the status 400.

Can you help me debug this?

The model on Hugging Face:
https://huggingface.co/stabilityai/stable-diffusion-2-1

The template:
```
---
PromptInfo:
 promptId: photoSD
 name: 🖼️ Generate a photo from Stable Diffusion
 description: select a text and photo will be generated using Stable Diffusion on Hugging Face
 author: 
 tags: huggingface, photo, stable-diffusion
 version: 0.0.1
config:
 append:
  bodyParams: false
  reqParams: true
 context: "prompt"
 output: '`\n![](${requestResults.data[0].url})`'
bodyParams:
 n: 1
 size: "512x512"
reqParams:
 url: "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2-1"
 headers:
  Authorization: "Bearer TOKEN”
---
{{selection}}, photo
```
