### ISSUE TITLE
Keep context in chatGPT conversation?

### ISSUE THREAD

**Issue by jankoc** [nhaouari/obsidian-textgenerator-plugin#102]
Is it possible to keep context in repeated chatGPT(gpt-3.5-turbo) calls? Now it seems like each call to text generator gpt-3.5-turbo loses the context of the previous call (or is there a setting I missed?).

**Comment by vratclarkson** [comment]
I came to raise this issue, @jankoc thanks for raising this issue. 

Hello there @nhaouari, many thanks for this plugin.

I came across this video and I thought I share it with you.

https://www.youtube.com/watch?v=Si0vFx_dJ5Y

Thank you for developing this plugin.

**Comment by nhaouari** [comment]
> Is it possible to keep context in repeated chatGPT(gpt-3.5-turbo) calls? Now it seems like each call to text generator gpt-3.5-turbo loses the context of the previous call (or is there a setting I missed?).

Hey @jankoc! 
Thanks for reaching out. To answer your question, currently each call to the text generator gpt-3.5-turbo is a one-shot deal and does not retain context from previous calls. However, the good news is that the context is very flexible so you can select any part of the document or even the entire document to work with. We suggest checking out this link http://text-gen.com/considered-context for more insights on how to consider context. 
Hope this helps!

**Comment by jankoc** [comment]
Thanks for getting back, @nhaouari. I know that I can add more text in the call, but the possibility to continue a dialogue with updated information with gps-3.5-turbo is really neat. Based on the openai API, it should be quite easy to retain context by sending the history of both sides of the conversation to the API (I've done it in Python), but you would need to store the conversation. I haven't looked enough into the plugin-structure of Obsidian to understand how easy it is to store information there, though. If I would have attemted to program it, I would have made a switch for "keep context", and in that case kept adding to the current "conversation" until it is too long (more than ~3000 words) or contect is cleared/new conversation started using a command/shortcut key. Anyway, thanks for  avery nice plugin, I'll keep using it also if you don't go down this road.

**Comment by acasto** [comment]
I've been thinking about this as well as my list of conversations on the ChatGPT site become unwieldly and I've been chatting more and more via a Python script from the command line, I was wondering if there was some easier way to get conversations into Obsidian than copy and pasting. Was thinking about possibly dumping them into a separate folder and then linking or transcluding as needed into other notes. Not sure what would be required to hold a conversation within Obsidian, but a standardish way to persist and retrieve in the chat format could be useful towards that end.

**Comment by acasto** [comment]
Would it be possible to make this a type of considered context or metadata? Like if you selected some text in format like:

me: question
ai: answer
me: another question
ai: answer

Could that be parsed into the JSON chat format? That way you wouldn't have to keep the context of a conversation as it would just be part of the text. After coming across a prompt format where they were feeding the output back in as input to be improved I was wondering what would happen if you dumped a conversation into text like this, corrected errors and whatnot, and then ran it again building off an improved context.

**Comment by aarons** [comment]
I explored a couple of workarounds for this, which work until the note hits the context limit. 

The three methods all center around sending the entire note to ChatGPT, and instructing it that it's receiving a chatlog, and should pick up where it left off. I also instruct it to include a separator, but I found in practice it was more helpful for me and didn't seem that necessary for the bot.

Here's an example using frontmatter. This would be used with the "generate text with metadata" command:

```
---
context: "You are Andrew Norvig, a relative of Andrew Ng and Peter Norving who is a great expert in AI, Programming, and Teaching others. Your goal is to assist the user in their programming needs."
rules: "Stay in character as Andrew Norvig. Focus on being as helpful as possible, while still being concise."
responses: "A history of your previous conversation with the user may be included, please keep that in mind when responding. It's ok to ask the user questions to better understand their needs and to help them ask better questions. Include three dashes (---) on a newline at the end of your response, to help separate responses."
---
```

Here's an example text-generator template that could be used instead:
```
---
PromptInfo:
 promptId: aiteacher
 name: AI Chat
 description: continues a conversation with ChatGPT about AI
 author: aarons
 tags: ai, programming, learning
 version: 0.0.1
---
Context: You are Andrew Norvig, a relative of Andrew Ng and Peter Norving, who is a great expert in AI, Programming, and Teaching others. Your goal is to assist the user with their programming needs. 

Rules: Stay in character as Andrew Norvig. Focus on being as helpful as possible while still being concise.

Strategy: It's ok to ask the user questions to understand their needs better and to understand where they might be lacking knowledge that will help them ask better questions.

Below is the history of your previous conversation with this user.  Please continue the conversation: 
{{context}}
```

In both cases, I was able to have an ongoing discussion until I hit the context limit.

I think if the context was dynamically trimmed down to fit within max_tokens (maybe the user could set the context to always be no more than 75% of max_tokens for example), then as long as max_tokens was high enough, then the user could continue to have an ongoing chat.
