### ISSUE TITLE
Cannot specify model in template file

### ISSUE THREAD

**Issue by kksharma1618** [nhaouari/obsidian-textgenerator-plugin#98]
I would like to specify model on templates. For example:
``` 
---
PromptInfo:
  promptId: rewrite
  name: ✏️ Rewrite, Paraphrase
  description: select a content and it will be rewriten.
  author: Noureddine
  tags: writing
  version: 0.0.1
bodyParams:
  model: text-curie-001
---

content:
{{context}}
prompt:
rewrite the content to make it more attractive

```

But when I do that it doesn't use that model. Also the template selection dropdown doesn't show title for template when I add bodyParams.model in it.
![image](https://user-images.githubusercontent.com/2723026/219795589-26665b24-46f5-4d66-b5b5-5fd5ec4e64ea.png)
